version: "3"
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./laravel:/var/www/
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
    - ./laravel:/var/www/
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:8.0.28
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tulip
      MYSQL_USER: akehi
      MYSQL_PASSWORD: ie3a18
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306


      
